### ISSUE TITLE
Add title

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p3-article#142]

**Comment by MadsHeilmann** [comment]
I am thinking maybe "Business intelligence with a focus on NOVA as a case study" or something like that

**Comment by SebastianMygind** [comment]
Maybe "Business intelligence through analytics, with Café NOVA as a case study".
Either one sounds good to me

**Comment by MadsHeilmann** [comment]
I like yours better tbh

**Comment by Danar435** [comment]
I have no ideas nor preferences for the title. But I like Sebastian's suggestion
