### ISSUE TITLE
Add more details regarding the explanation of the back end architecture diagram

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p3-article#159]

**Comment by Danar435** [comment]
There is already a well detailed explanation for the diagram, I believe that latex placed the diagram lower down from the explanation and Tung just did not see it. I've fixed the placement in my PR. Of course if you feel the need to add more details, then be my guest.

**Comment by MadsHeilmann** [comment]
Ah yeah i remember now that he just hadnt seen it - my bad. We can just close this then.
