### ISSUE TITLE
Add tilstandsdiagram

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p3-article#169]
We have them in Application domain analysis. However it should be in problem domain analysis

**Comment by MadsHeilmann** [comment]
Maybe its unneccesarry. However a part of the OOAD method

**Comment by MadsHeilmann** [comment]
Maybe lets fuck it off?

**Comment by Danar435** [comment]
I dunno, I feel like if we had something important that we were missing or was wrong in the report, then Tung would've let us know. The analysis sections have been finished for a long time now
