### ISSUE TITLE
Using "order" in the report and software

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p3-article#65]
An order in my opinion is what the customer gives the barista, who then prepares the order.
Afterwards the customer pays for the product and the order is fulfilled.
In the system is now a transaction and not an order.
In my opinion these are very different things that occur at different times in the exchange.

Therefore i propose that we change the language from "order" to "transaction" as that is more accurate for the information that our solution will be processing.

Another point is that if we were making software that could take the order, save it and delete it when fulfilled, like on the McDonald screens, then "order" would be the right term. However, as we are not, it is inaccurate.

**Comment by audio-engineer** [comment]
> In the system is now a transaction and not an order.

No, a transaction is the capturing of payment, not fulfilling an order. Transactions belong to the financial domain, and orders to the practical, which is what we focus on.

> Another point is that if we were making software that could take the order, save it and delete it when fulfilled, like on the McDonald screens, then "order" would be the right term. However, as we are not, it is inaccurate.

This is also not true. All orders, no matter what status they have (accepted, rejected, canceled, etc.) are always persisted in every system, and they always refer back to the initial customer request. Also McDonald's.

Also, the EPOS's database also saves the data as "order" in the database, and so does any sensible commerce software.

**Comment by MadsHeilmann** [comment]
Okay makes sense. I didnt realize it was tagged as "order" in the data as well
