### ISSUE TITLE
Data visualization analysis

### ISSUE THREAD

**Issue by audio-engineer** [audio-engineer/aau-p3-article#9]
Initial analysis and thoughts about how the client's data can be interpreted and visualized by our solution

**Comment by Saeed-07** [comment]
What kind of data you need to visualize? I think I can help you with that.

**Comment by audio-engineer** [comment]
@Saeed-07 Thank you. It's a university project so all work will be done by the project group internally.

**Comment by Saeed-07** [comment]
No problem at all! Good luck with the project!
